# Generated by Django 4.1.3 on 2022-12-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gost33259Flange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_passage', models.CharField(max_length=6)),
                ('pn', models.CharField(max_length=6)),
                ('d2', models.CharField(blank=True, max_length=6, null=True)),
                ('d3', models.CharField(blank=True, max_length=6, null=True)),
                ('d4', models.CharField(blank=True, max_length=6, null=True)),
                ('d5', models.CharField(blank=True, max_length=6, null=True)),
                ('d6', models.CharField(blank=True, max_length=6, null=True)),
                ('d7', models.CharField(blank=True, max_length=6, null=True)),
                ('d8', models.CharField(blank=True, max_length=6, null=True)),
                ('d9', models.CharField(blank=True, max_length=6, null=True)),
                ('d10', models.CharField(blank=True, max_length=6, null=True)),
                ('d11', models.CharField(blank=True, max_length=6, null=True)),
                ('b2_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h1_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h2_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h3_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h4_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h5_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('dm', models.CharField(blank=True, max_length=6, null=True)),
                ('dn', models.CharField(blank=True, max_length=6, null=True)),
                ('d1_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('b_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h', models.CharField(blank=True, max_length=6, null=True)),
                ('d', models.CharField(blank=True, max_length=6, null=True)),
                ('d1', models.CharField(blank=True, max_length=6, null=True)),
                ('d_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('n_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'ГОСТ 33259-2015',
                'verbose_name_plural': 'ГОСТ 33259-2015',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gost33259Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_fl', models.CharField(max_length=6)),
                ('flange_surface', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'уплотнительные поверхности',
                'verbose_name_plural': 'Уплотнительная поверхность',
            },
        ),
        migrations.CreateModel(
            name='Gost33259Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fl', models.CharField(max_length=6)),
                ('flange_drawing', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'типы',
                'verbose_name_plural': 'Тип фланца',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=200)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gost.categorydoc', verbose_name='Категории')),
            ],
        ),
    ]
