# Generated by Django 4.1.3 on 2022-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gost33259_flange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_passage', models.CharField(max_length=6)),
                ('pn', models.CharField(max_length=6)),
                ('d2', models.CharField(blank=True, max_length=6, null=True)),
                ('d3', models.CharField(blank=True, max_length=6, null=True)),
                ('d4', models.CharField(blank=True, max_length=6, null=True)),
                ('d5', models.CharField(blank=True, max_length=6, null=True)),
                ('d6', models.CharField(blank=True, max_length=6, null=True)),
                ('d7', models.CharField(blank=True, max_length=6, null=True)),
                ('d8', models.CharField(blank=True, max_length=6, null=True)),
                ('d9', models.CharField(blank=True, max_length=6, null=True)),
                ('d10', models.CharField(blank=True, max_length=6, null=True)),
                ('d11', models.CharField(blank=True, max_length=6, null=True)),
                ('b2_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h1_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h2_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h3_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h4_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h5_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('dm', models.CharField(blank=True, max_length=6, null=True)),
                ('dn', models.CharField(blank=True, max_length=6, null=True)),
                ('d1_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('b_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('h', models.CharField(blank=True, max_length=6, null=True)),
                ('d', models.CharField(blank=True, max_length=6, null=True)),
                ('d1', models.CharField(blank=True, max_length=6, null=True)),
                ('d_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('n_lower', models.CharField(blank=True, max_length=6, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gost33259_surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_fl', models.CharField(max_length=6)),
                ('flange_surface', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gost33259_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fl', models.CharField(max_length=6)),
                ('flange_drawing', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
